### PR TITLE
Parsing more complex cases of YAML files

### PR DESCRIPTION
**Pull request by kapekost**
the fix allows git2consul to parse values including arrays, and multiple levels, including objects.
the sample file can be found in tests' directory and the tests are a sample of the cases that are passing.

side-note:
one of the tests were already failing, I commented out and fixed a typo in a variable

> on a mac, 

> kapekost:kapekost kapekost$ node -v
> v5.12.0

> Consul v0.7.3
> Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

### CODE REVIEW

**Comment by kapekost** [comment]
Travis is failing the same test which I re-enabled, but the exit code is a 0 for the build process finishing smoothly.
Do we need a workaround for that to fail Travis report when a test is failing?

**Comment by breser** [comment]
Can you rebase this on master so that you'll have the fixes for the busted test suite?

**Comment by kapekost** [comment]
something is failing in the tests when I resolved the conflict in package.json, I will investigate and push a fix soon

**Comment by kapekost** [comment]
oddly, the only difference I see is the nvm version on Travis

**Comment by johntdyer** [comment]
Any luck on this?

**Pull request closed without merging**
